### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by Africaggy** [overlord1123/DigitalFilters#2]
Thanks for your code first.But I want to know how to use it? I have a trajectory and  I want to apply in "franka-panda"robot .So how to input my many points and get output points? 
I am glad to hear your reply!thank you

**Comment by jimmyberg** [comment]
Why do you want to input your trajectory into a low pass filter? Do you intent to interpolate in order to find intermediate values between two known points? I would suggest you could use either linear interpolation(easy), cubic interpolation(hard) or something similar. Currently not included here.

Low and high pass filters are usually intended to filter input data from like ADC data. Imagine recording sound and you want to filter out high frequency noise. This is when you apply a low pass filter.

Good luck!
